# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

github_archive_1:
  outputs:
    dev:
      dataset: {{ variables('Dataset_Id') }}
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../../{{ variables('Google_credentials') }}
      location: US
      method: service-account
#      priority: interactive
      project:  {{ variables('PROJECT_ID') }} #github-data-analysis-419818
      threads: 4
      type: bigquery
      impersonate_service_account: github-service@github-data-analysis-419818.iam.gserviceaccount.com
  target: dev
