bg_github_archive:
  outputs:
    dev:
      dataset: {{ env_var('Dataset_Id') }}
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../../{{ env_var('Google_credentials') }}
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}" #github-data-analysis-419818
      threads: 4
      type: bigquery
  target: dev
